"""Universal preprocessing and quality evaluation pipeline for ML datasets."""

from preprocessing.loader import (
    LoadReport,
    LoadResult,
    format_load_summary,
    load_csv,
)
from preprocessing.missing import (
    normalize_missing,
    drop_sparse_columns,
    drop_rows,
    impute,
    apply_impute,
    NormalizeMissingResult,
    MissingReport,
    DropSparseResult,
    DropSparseReport,
    DropRowsResult,
    DropRowsReport,
    ImputationResult,
    ImputationReport,
    DEFAULT_NA_TOKENS,
)
from preprocessing.heatmap import (
    plot_missing_heatmap,
    plot_minmax_heatmap,
    plot_correlation_heatmap,
    plot_outlier_heatmap,
    rank_correlations,
)
from preprocessing.transforms import (
    log_transform,
    inverse_log_transform,
    onehot_encode,
    parse_dates,
    to_numeric,
    scale,
    apply_scale,
    OneHotResult,
    OneHotReport,
    DateParseResult,
    DateParseReport,
    ToNumericResult,
    ToNumericReport,
    ScaleResult,
    ScaleReport,
    ColumnScaling,
)
from preprocessing.outliers import (
    detect_outliers,
    handle_outliers,
    apply_outliers,
    OutlierDetectionResult,
    OutlierHandlingResult,
    OutlierReport,
)
from preprocessing.scatter import (
    plot_kde_scatter,
    plot_dbscan_scatter,
    plot_elliptic_scatter,
    plot_strip,
    plot_outlier_scatter,
)
from preprocessing.distribution import (
    profile_columns,
    count_variations,
    compare_datasets,
)
from preprocessing.pipeline import (
    Pipeline,
    PipelineResult,
    StepResult,
    detect_and_handle_outliers,
)
from preprocessing.formatters import format_report
from preprocessing.filters import (
    find_rows,
    find_coords,
    set_cells_to_nan,
    SetCellsResult,
    SetCellsReport,
)
from preprocessing.splitting import (
    split_dataset,
    SplitResult,
    SplitReport,
)
from preprocessing.plots import (
    plot_histogram,
    plot_violin,
    plot_before_after,
    plot_value_counts,
    plot_target_correlation,
    plot_outlier_consensus,
    plot_outlier_ranking,
)

__version__ = "0.1.0"

__all__ = [
    "LoadReport",
    "LoadResult",
    "format_load_summary",
    "load_csv",
    "normalize_missing",
    "drop_sparse_columns",
    "drop_rows",
    "impute",
    "NormalizeMissingResult",
    "MissingReport",
    "DropSparseResult",
    "DropSparseReport",
    "DropRowsResult",
    "DropRowsReport",
    "ImputationResult",
    "ImputationReport",
    "apply_impute",
    "DEFAULT_NA_TOKENS",
    "plot_missing_heatmap",
    "plot_minmax_heatmap",
    "plot_correlation_heatmap",
    "plot_outlier_heatmap",
    "rank_correlations",
    "log_transform",
    "inverse_log_transform",
    "onehot_encode",
    "parse_dates",
    "to_numeric",
    "scale",
    "apply_scale",
    "OneHotResult",
    "OneHotReport",
    "DateParseResult",
    "DateParseReport",
    "ToNumericResult",
    "ToNumericReport",
    "ScaleResult",
    "ScaleReport",
    "ColumnScaling",
    "detect_outliers",
    "handle_outliers",
    "apply_outliers",
    "OutlierDetectionResult",
    "OutlierHandlingResult",
    "OutlierReport",
    "plot_kde_scatter",
    "plot_dbscan_scatter",
    "plot_elliptic_scatter",
    "plot_strip",
    "plot_outlier_scatter",
    "profile_columns",
    "count_variations",
    "compare_datasets",
    "Pipeline",
    "PipelineResult",
    "StepResult",
    "detect_and_handle_outliers",
    "format_report",
    "find_rows",
    "find_coords",
    "set_cells_to_nan",
    "SetCellsResult",
    "SetCellsReport",
    "split_dataset",
    "SplitResult",
    "SplitReport",
    "plot_histogram",
    "plot_violin",
    "plot_before_after",
    "plot_value_counts",
    "plot_target_correlation",
    "plot_outlier_consensus",
    "plot_outlier_ranking",
]
